/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package me.veir1.gui;

import me.veir1.gui.entity.Entity;
import me.veir1.gui.storage.PeopleStorage;

import javax.swing.*;

/**
 *
 * @author uss
 */
public class FormCliente extends javax.swing.JFrame {

    /**
     * Creates new form FormCliente
     */
    public FormCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        blockButtonGroup = new javax.swing.ButtonGroup();
        panelApp = new javax.swing.JPanel();
        labelRut = new javax.swing.JLabel();
        fieldNombre = new javax.swing.JTextField();
        labelNombre = new javax.swing.JLabel();
        fieldRut = new javax.swing.JTextField();
        panelBlock = new javax.swing.JPanel();
        optBloque1 = new javax.swing.JRadioButton();
        optBloque2 = new javax.swing.JRadioButton();
        buttonEnviar = new javax.swing.JButton();
        buttonExit = new javax.swing.JButton();
        labelCorreo = new javax.swing.JLabel();
        fieldCorreo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro de alumnos en ayudantía");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        panelApp.setBackground(new java.awt.Color(153, 153, 153));
        panelApp.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        panelApp.setToolTipText("Datos Personales");
        panelApp.setFocusTraversalPolicyProvider(true);
        panelApp.setName("datosPersonales"); // NOI18N

        labelRut.setText("RUT");

        labelNombre.setText("Nombre Completo");

        panelBlock.setBorder(javax.swing.BorderFactory.createTitledBorder("Bloque"));
        panelBlock.setToolTipText("Bloque");

        blockButtonGroup.add(optBloque1);
        optBloque1.setText("Bloque 1 : 4:00 - 4:40");
        optBloque1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optBloque1ActionPerformed(evt);
            }
        });

        blockButtonGroup.add(optBloque2);
        optBloque2.setText("Bloque 2: 4:40 - 5:40");
        optBloque2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optBloque2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBlockLayout = new javax.swing.GroupLayout(panelBlock);
        panelBlock.setLayout(panelBlockLayout);
        panelBlockLayout.setHorizontalGroup(
            panelBlockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBlockLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(panelBlockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(optBloque1)
                    .addComponent(optBloque2))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        panelBlockLayout.setVerticalGroup(
            panelBlockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBlockLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(optBloque1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(optBloque2)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        buttonEnviar.setText("Enviar");
        buttonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEnviarActionPerformed(evt);
            }
        });

        buttonExit.setText("Salir");
        buttonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExitActionPerformed(evt);
            }
        });

        labelCorreo.setText("Correo");

        javax.swing.GroupLayout panelAppLayout = new javax.swing.GroupLayout(panelApp);
        panelApp.setLayout(panelAppLayout);
        panelAppLayout.setHorizontalGroup(
            panelAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAppLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panelAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAppLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(panelAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelRut, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNombre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(fieldNombre)
                                .addComponent(fieldRut, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(fieldCorreo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelAppLayout.createSequentialGroup()
                        .addComponent(buttonEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(panelAppLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(panelBlock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );
        panelAppLayout.setVerticalGroup(
            panelAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAppLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(panelAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelRut, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 32, Short.MAX_VALUE)
                .addComponent(panelBlock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(panelAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonEnviar)
                    .addComponent(buttonExit))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelApp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelApp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void optBloque1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optBloque1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optBloque1ActionPerformed

    private void optBloque2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optBloque2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optBloque2ActionPerformed

    private void buttonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_buttonExitActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void buttonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEnviarActionPerformed
        String data = "";
        if (fieldRut.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "Por favor ingrese el RUT del alumno a procesar", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }                                
        if (fieldNombre.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "Por favor ingrese los nombres del alumno a procesar", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (fieldCorreo.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "Por favor ingrese el email del alumno a procesar", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (blockButtonGroup.getSelection() == null) {
            JOptionPane.showMessageDialog(null, "Por favor seleccione el bloque del alumno a registrar", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        char block;
        if (optBloque1.isSelected()) {
            block = 'A';
        } else {
            block = 'B';
        }

        final Entity entity = new Entity(fieldRut.getText(), fieldNombre.getText(), fieldCorreo.getText(), block);
        peopleStorage
                .addEntity(
                        entity);

        fieldRut.setText("");
        fieldNombre.setText("");
        fieldCorreo.setText("");

        blockButtonGroup.clearSelection();

    }//GEN-LAST:event_buttonEnviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException |
                 UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormCliente().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup blockButtonGroup;
    private javax.swing.JButton buttonEnviar;
    private javax.swing.JButton buttonExit;
    private javax.swing.JTextField fieldCorreo;
    private javax.swing.JTextField fieldNombre;
    private javax.swing.JTextField fieldRut;
    private javax.swing.JLabel labelCorreo;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelRut;
    private javax.swing.JRadioButton optBloque1;
    private javax.swing.JRadioButton optBloque2;
    private javax.swing.JPanel panelApp;
    private javax.swing.JPanel panelBlock;
    // End of variables declaration//GEN-END:variables
    private PeopleStorage peopleStorage = new PeopleStorage("ayudantias.txt");
}
